"""add lesson column into schedules

Revision ID: 2386f20e7d77
Revises: ab38fd4722d9
Create Date: 2022-01-24 14:41:35.457522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2386f20e7d77'
down_revision = 'ab38fd4722d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('lesson', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'lesson')
    # ### end Alembic commands ###
